### PR TITLE
Introduce CI with HIP

### PR DESCRIPTION
**Pull request by rasolca**
- [x] build image
- [x] deploy image
- [ ] runner
- [ ] full test

### CODE REVIEW

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try-

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try-

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by msimberg** [comment]
Should we merge this into #459, at least to get building of tests enabled before #459 goes into master? Actual testing may need to come later (I don't know what the situation is on that side).

**Comment by rasolca** [comment]
> Should we merge this into #459, at least to get building of tests enabled before #459 goes into master? Actual testing may need to come later (I don't know what the situation is on that side).

Unfortunately #459 is on a fork. What I can do is to clean it up and push the changes there it everyone agrees.

**Comment by rasolca** [comment]
Changes added to #459

**Pull request closed without merging**
