### PR TITLE
Add NOT_YET_IMPLEMENTED assertion

### LINKED ISSUE #243: Common way to manage NOT IMPLEMENTED cases
I think it is worth adding a common way to manage all the cases that are not yet implemented.

### PR DESCRIPTION
**Pull request by albestro**
Close #243 

The starting point is a very trivial implementation.

As soon as we agree on a solution, I will add few lines of documentation and I will employ it in the codebase (e.g. `Auxiliary::norm`).

### CODE REVIEW

**Comment by teonnik** [comment]
This looks good to me but I don't understand what the problem with `DLAF_ASSERT(false, "Not implemented sth sth ...")` is?

**Comment by albestro** [comment]
> but I don't understand what the problem with
> 
> ```
> DLAF_ASSERT(false, "Not implemented sth sth ...")
> ```
> 
> is?

I thought the usage was a bit "forced". But, if we agree that it is preferable to use a `DLAF_ASSERT` instead of a dedicated one for the `NOT_YET_IMPLEMENTED`, we can just skip this. No problem.

What do you think @rasolca @Sely85 ?

**Comment by teonnik** [comment]
If you are referring to this:

```
switch (norm_type) {
    case lapack::Norm::One:
    case lapack::Norm::Two:
    case lapack::Norm::Inf:
    case lapack::Norm::Fro:
      DLAF_ASSERT(false, "not yet implemented", lapack::norm2str(norm_type));
      return {};
    case lapack::Norm::Max:
      switch (uplo) {
        case blas::Uplo::Lower:
          return internal::mc::norm_max_L(grid, rank, A);
        case blas::Uplo::Upper:
        case blas::Uplo::General:
          DLAF_ASSERT(false, "not yet implemented", lapack::norm2str(norm_type), blas::uplo2str(uplo));
          return {};
        default:
          return {};
      }
    default:
      return {};
  }
```

this can also be written as 

DLAF_ASSERT(norm_type == lapack::Norm::Max, "Not yet implemented!", norm_type);
DLAF_ASSERT(uplo == blas::Uplo::Lower, "Not yet implemented!", uplo);

**Comment by Sely85** [comment]
> > but I don't understand what the problem with
> > ```
> > DLAF_ASSERT(false, "Not implemented sth sth ...")
> > ```
> > is?
> 
> I thought the usage was a bit "forced". But, if we agree that it is preferable to use a `DLAF_ASSERT` instead of a dedicated one for the `NOT_YET_IMPLEMENTED`, we can just skip this. No problem.
> 
> What do you think @rasolca @Sely85 ?

I would prefer to use a dedicated one because it would be easier to "spot", to avoid confusing preconditions check with features that we still need to implement for example. 
By the way, both approaches work well.

**Comment by albestro** [comment]
@rasolca @msimberg what do you think about this? should we close it or merge it?

**Comment by msimberg** [comment]
IMO this is quite nice, since it's not a lot of code but it adds quite a bit of clarity. The macro should probably add the message "Not yet implemented" for the macro to make sense. `UNIMPLEMENTED` instead of `NOT_YET_IMPLEMENTED`?

I think using `DLAF_ASSERT` is also fine, this is not such a big deal.

**Comment by albestro** [comment]
This should sum up all our point of views.

I also applied it in the code, since I think that in one way or another, at the end of this PR, these code lines should be unified.

**Review by teonnik — APPROVED** [review]

**Comment by rasolca** [comment]
bors try

**Review by rasolca — APPROVED** [review]

**Review by Sely85 — APPROVED** [review]
LGTM

**Review by rasolca — CHANGES_REQUESTED** [review]
It is not needed to use blaspp utilities to print the enums. We provide output operators for them (currently even two copies (see #281), which will be fixed by #282).

**Comment by albestro** [comment]
@rasolca as soon as we merge #282 I will migrate completely to them 😉

**Comment by albestro** [comment]
bors try

after rebase where operator<< for blas and lapack enums is available

**Review by rasolca — APPROVED** [review]

**Comment by rasolca** [comment]
bors try

**Pull request merged**
