### PR TITLE
CMake updates and fixes

### PR DESCRIPTION
**Pull request by albestro**
Some updates and fixes on the CMake side.

- Update FindLAPACK
- Use standard LAPACK::LAPACK target
- Improve MKL selection of targets

### CODE REVIEW

**Comment by albestro** [comment]
bors try

**Comment by albestro** [comment]
bors try

**Comment by albestro** [comment]
bors try

**Comment by albestro** [comment]
bors try

**Review by rasolca — APPROVED** [review]

**Pull request merged**
