### PR TITLE
Fix FindMKL on mac + minor improvements

### PR DESCRIPTION
**Pull request by albestro**
- Use updated version of FindMKL from external repository `cmake-recipes`
- Add check about MKL target existing
- ~Use alias target `LAPACK::LAPACK` (mirroring the target from standard cmake FindLAPACK)~

Opened it in draft mode, waiting for PR approval of the updated version of FindMKL

### CODE REVIEW

**Comment by albestro** [comment]
About FindMKL, it has been updated with the last version that works correctly also on macOS.

**Comment by albestro** [comment]
bors try

**Review by teonnik — APPROVED** [review]

**Comment by albestro** [comment]
bors try

**Comment by albestro** [comment]
bors try

**Comment by albestro** [comment]
bors try

**Comment by albestro** [comment]
I reverted the change about using the ALIAS target for LAPACK...I was not able to quickly reproduce it.

For the moment it is more relevant to just fix and update FindMKL, we can think about doing it later.

**Pull request merged**
