### PR TITLE
Use docker hub token for pulling images in CI

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Comment by msimberg** [comment]
Note: I tested this on pika's CI and it successfully logs in with the credentials. I don't know how to tell if it's actually using the credentials for pulling the image though, and I don't really have ideas on how to confirm that. If you have some ideas please let me know.

I've set up a token in the CI settings.

**Comment by msimberg** [comment]
cscs-ci run

**Comment by msimberg** [comment]
cscs-ci run

**Review by rasolca — APPROVED** [review]
CI didn't rebuild the base image, but I confirm that it works as expected as I merged it in in #1140.

**Pull request merged**
