### PR TITLE
Explicit Template Instantiations

### PR DESCRIPTION
**Pull request by teonnik**
This PR addresses https://github.com/eth-cscs/DLA-Future/issues/169 . ETI is implemented for `Matrix`, `Tile` and a few other types using the `extern` approach (see https://github.com/eth-cscs/DLA-Future/issues/169). 

Note that separating the implementation of some templated functions into a `tpp` file is not needed for the purposes of ETI. We can move the definitions into the `.h` file if there is consensus. That will save us some boilerplate.

### CODE REVIEW

**Comment by teonnik** [comment]
Note that the only difference between the DECL and INST macros is an `extern` parameter. There is some room for reduction on the boilerplate.

**Comment by teonnik** [comment]
> I'm wondering if ETI of the full object can influence inlining of small methods. Do you know how it works?

Yes it does, same as anything else in a cpp file, inlining is no longer possible UNLESS we use LTO (link-time optimization). An approach to alleviate the issue, is to perhaps only instantiate selected member methods of the class.

> Moreover as mentioned by you I would reduce a bit code duplication. I have a suggestion: https://godbolt.org/z/QhKzTc . What do you think?

I like the DECL/INST macros (prefixed with DLAF_) and the extra parameter on the A_ETI/B_ETI macros (I'd put KEYWORDS first) but going any further seems like too much macro magic and is a bit harder to read. I think it's also fine if we specify `extern template` and `extern` directly into the A_ETI and B_ETI macros. That way we won't have to keep including a header for DECL/INST macros. If we want to shorten the above, we can add the template keyword and pass only `extern` for DECL and nothing for INST. Apparently macros with empty parameters are allowed:

https://stackoverflow.com/questions/7666344/are-empty-macro-arguments-legal-in-c11

**Comment by rasolca** [comment]
> Yes it does, same as anything else in a cpp file, inlining is no longer possible UNLESS we use LTO (link-time optimization). An approach to alleviate the issue, is to perhaps only instantiate selected member methods of the class.

This is what puzzles me, keeping in mind that all the members defined in a class are marked with inline:
In the usual .h and .cpp structure, the .h contains the class declaration + inlined members definition + other members declaration, while in the .cpp you find the other member definition.
The compiler has full control (can decide to inline or not) on members marked as inline (either implicitly in the class declaration or explicitly), while it has no control on members defined in the .cpp file.

The question is how ETI deal with member functions which as been declared as inline.

**Comment by rasolca** [comment]
Apparently inline marked methods are not instantiated and can be inlined with ETI too:
https://godbolt.org/z/vTXPB9

Therefore if you want ETI to have some impact the "long" members has to be defined outside 
the class declaration and therefore I would keep the .h and .tpp distinction to underline the difference.

**Comment by teonnik** [comment]
It seems that the compiler decides whether to instantiate a method or to inline it depending on whether it thinks the method is worth instantiation. For gcc and clang, defining the method outside of the class seems to encourage them to not inline it but it is not necessary as can be seen from this : https://godbolt.org/z/pd5VlE .

**Comment by rasolca** [comment]
Of course, you can always try to steer compiler decisions with attributes (inline, force_inline and noinline), but I find more natural the distinction that inline methods are defined in the class declaration and non inline methods outside as specified by the standard.

**Comment by teonnik** [comment]
The only reason I used `__attribute__((noinline))` was to illustrate that the definition of the method can be inside the class and still e instantiated. You don't need the attribute to achieve that if the method is deemed complicated enough not to be worth inlining. In fact, that is what I tried initially, after adding a few lines with a bunch std::string, std::vector and std::cout, it was no longer inlined and clang just referenced the instantiation (gcc stubbornly kept optimizing though).

**Pull request merged**
