### PR TITLE
Remove unnecessary `keep_future`s from merge implementation

### LINKED ISSUE #590: Remove unnecessary `keep_future` in `tridiag_solver`
https://github.com/eth-cscs/DLA-Future/blob/8de7224ee8c51b9bd1f580fdecdcdf2e86a6348a/include/dlaf/eigensolver/tridiag_solver/merge.h#L232-L238 can be fixed after pika 0.6.0.

### PR DESCRIPTION
**Pull request by msimberg**
Fixes #590.

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Review by teonnik — APPROVED** [review]

**Comment by msimberg** [comment]
This will conflict with #617.

**Comment by msimberg** [comment]
bors try

**Comment by rasolca** [comment]
bors try-

**Comment by msimberg** [comment]
bors try

**Review by rasolca — APPROVED** [review]

**Pull request merged**
