### PR TITLE
Distributed tridiagonal solver (GPU)

### PR DESCRIPTION
**Pull request by teonnik**
~Depends on https://github.com/eth-cscs/DLA-Future/pull/718 .~

### CODE REVIEW

**Comment by teonnik** [comment]
bors try

**Comment by teonnik** [comment]
bors try

**Comment by teonnik** [comment]
bors try -

**Comment by teonnik** [comment]
bors try

**Comment by teonnik** [comment]
bors try

**Comment by teonnik** [comment]
This is ready for review and has Givens rotations on MC. Once https://github.com/eth-cscs/DLA-Future/pull/718 is in, I can make the corresponding adjustments for the GPU. However, the PR doesn't depend on it currently and can be merged as it is if that is preferred.

**Review by rasolca — APPROVED** [review]

**Pull request merged**
