### PR TITLE
Bump gcc version using ubuntu:20.04 image

### PR DESCRIPTION
**Pull request by rasolca**
Updated the base CI container from Ubuntu 18.04 to Ubuntu 20.04.
This allow to use gcc 9 and Cuda 11.

Upgrading to gcc9 a couple of extra warnings appeared and have been fixed.

### CODE REVIEW

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Review by albestro — APPROVED** [review]
LGTM

**Comment by haampie** [comment]
> @haampie Any news about Missing gitlab-runner. Uploading artifacts is disabled.

looking into that now

**Comment by haampie** [comment]
works for me: https://gitlab.com/cscs-ci/ci-testing/artifact_test/-/jobs/1159527187

i've added `gitlab-runner` to the PATH yesterday, that might be it

**Pull request merged**
