### PR TITLE
Fix warnings on GCC (after CMake bug fix)

### PR DESCRIPTION
**Pull request by albestro**
This PR is just a side-PR of #348.

It is going to be merged into that one and then they will be merged on master all together.

### CODE REVIEW

**Comment by albestro** [comment]
There is still a problem to be solved in lapack tests.

I'm going to push a commit with a fix but it requires a better definition of the maximum error allowed, otherwise the test fails.

**Comment by albestro** [comment]
bors try

**Comment by albestro** [comment]
bors try

**Comment by albestro** [comment]
bors try

**Comment by albestro** [comment]
The problem there was in the previous failed build from bors, it seems was due to GCC 7.

The problem was
```
/DLA-Future/include/dlaf/types.h:123:54: error: conversion to 'long unsigned int' from 'const int' may change the sign of the result [-Werror=sign-conversion]
   DLAF_ASSERT_MODERATE(std::numeric_limits<U>::max() >= static_cast<std::size_t>(signed_value),
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

After rebasing it on the new master which uses GCC 9, it went away (and I don't see any related change).

**Comment by albestro** [comment]
bors try
(after switching from functional cast to static_cast)

**Comment by albestro** [comment]
bors try

(let's try again)

**Review by rasolca — APPROVED** [review]

**Comment by albestro** [comment]
I will merge it by myself (it will merged in another PR, not on master), just waiting if @msimberg would like to give a quick feedback. 😉

**Pull request merged**
