### PR TITLE
Add codecov reports

### PR DESCRIPTION
**Pull request by haampie**
Adds a third build + test where DLA-Future is compiled with `-g -O0 -fprofile-arcs -ftest-coverage`. It should upload reports to codecov.io (a link should appear in the logs on gitlab).

### CODE REVIEW

**Comment by haampie** [comment]
bors try

**Comment by haampie** [comment]
bors try

**Comment by haampie** [comment]
bors try-

**Comment by haampie** [comment]
bors try

**Comment by haampie** [comment]
bors try

**Comment by haampie** [comment]
bors try

**Comment by haampie** [comment]
So in PRs the report is currently a bit hidden: via the bors commit, click the status icon, go to the gitlab pipelines, click [codecov test], and below inside the logs you find a link:

```
View reports at https://codecov.io/github/eth-cscs/DLA-Future/commit/34a79a2a8181e82cd69850481f6a9dfc59465215
```

With the current setup it should run by default on commits in master, and I've added a codecov badge to the readme with a link to the reports.

**Comment by haampie** [comment]
Since codecov has issues pulling code from github, let me try by pulling it from gitlab instead

bors try

**Comment by haampie** [comment]
:(

>  slurmstepd: error: *** STEP 22252199.2 ON nid00413 CANCELLED AT 2020-04-28T16:19:50 ***

bors try

**Comment by haampie** [comment]
bors try

**Comment by haampie** [comment]
That works, so now it uploads both for the github and gitlab repo:

https://codecov.io/github/eth-cscs/DLA-Future/commit/f8a0b0950107c51028c22c9caf49136f88c8b9fc

https://codecov.io/gitlab/cscs-ci:eth-cscs/DLA-Future/commit/f8a0b0950107c51028c22c9caf49136f88c8b9fc

This PR is done then :)

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
Note: bors test failed because of ongoing work.
(Test added to CI not implemented here.)

**Pull request merged**
