### PR TITLE
Namespace (SCA)LAPACK CMake modules with DLAF to avoid conflicts with other packages

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Comment by msimberg** [comment]
cscs-ci run

**Comment by msimberg** [comment]
cscs-ci run

**Comment by msimberg** [comment]
CI (rosa) is having issues, but there were some pipelines that finished ok with this, so I think this is working as intended (I also tested it manually and in a CP2K stack; note that building with spack requires the spack package change).

I admit I find the `FindDLAF_SCALAPACK.cmake` filename ugly, but not as ugly as having `DLAFSCALAPACK_INCLUDE_DIR` etc. CMake allows the module filename (i.e. the part after `Find`) to not match the package name used inside `FindX.cmake`, but it gives a warning about it potentially being confusing (with good reason). So I ended up with `FindDLAF_SCALAPACK.cmake` and `DLAF_SCALAPACK_X` variable names. Let me know if you think some other scheme would look better.

**Comment by RMeli** [comment]
I built https://github.com/eth-cscs/alps-uenv/pull/135 with the addition of
```
  # pika
  - boost
  - fmt
  - spdlog
  - hwloc
  - mimalloc
  - pika@0.26.1
  # DLA-Future
  - blt
  - camp
  - umpire
  - whip
  - lapackpp
  - blaspp
  - dla-future@git.cmake-modules-namespace=master +mpi_gpu_aware
  - dla-future-fortran
```
and the build completed successfully.

**Comment by msimberg** [comment]
cscs-ci run

**Review by rasolca — APPROVED** [review]

**Comment by msimberg** [comment]
cscs-ci run

**Pull request merged**
