### PR TITLE
Fix CI workaround for custom build directory

### PR DESCRIPTION
**Pull request by albestro**
Just discovered this new option `spack develop --build-directory` that I expect it to do what we were looking for, i.e. build in a custom path.

### CODE REVIEW

**Comment by albestro** [comment]
cscs-ci run

**Review by msimberg — APPROVED** [review]
Much nicer, thanks!

**Review by RMeli — APPROVED** [review]
LGTM. Already ported to https://github.com/eth-cscs/DLA-Future-Fortran/pull/1.

**Comment by albestro** [comment]
cscs-ci run

**Review by rasolca — APPROVED** [review]

**Pull request merged**
