### PR TITLE
Use pika 0.21 and oneapi MKL in CI

### LINKED ISSUE #1074: Migrate CI from using `intel-mkl` to `intel-oneapi-mkl`
IntelMKL is now deprecated in favour of Intel OneAPI MKL. This change is reflected also in spack, which sooner or later might bite us about the usage of a deprecated package (not sure, since we are using it as an external package). Even if it is not going to bite us, it is reasonable to migrate the CI to the newer oneMKL.

With #1073 we start supporting it both in CMake and in the `dla-future` package, so this task aims just at what has to be done for the CI in order to migrate.

Currently, the CI does not use spack to install MKL, and we install it independently as external package, so that we can keep low the space utilisation by installing just what is needed and also cleaning up unused stuff.

### PR DESCRIPTION
**Pull request by rasolca**
Closes #1074

Depends on 
- [x] on #1073
- [ ] fix of `intel-oneapi-mkl` package https://github.com/spack/spack/pull/42087

### CODE REVIEW

**Comment by rasolca** [comment]
cscs-ci run

**Comment by albestro** [comment]
cscs-ci run

**Comment by albestro** [comment]
cscs-ci run

**Comment by albestro** [comment]
cscs-ci run

**Comment by albestro** [comment]
cscs-ci run

**Comment by rasolca** [comment]
cscs-ci run

**Comment by albestro** [comment]
https://github.com/spack/spack/issues/38238 is the reference for the change in https://github.com/eth-cscs/DLA-Future/pull/1077/commits/3f9353f60d6358ddf24cf74392da32c1632e1afe

**Comment by rasolca** [comment]
cscs-ci run

**Comment by albestro** [comment]
cscs-ci run

**Comment by rasolca** [comment]
cscs-ci run

**Comment by rasolca** [comment]
cscs-ci run

**Comment by rasolca** [comment]
cscs-ci run

**Review by albestro — APPROVED** [review]
LGTM

**Review by msimberg — APPROVED** [review]

**Pull request merged**
