### PR TITLE
CI: Small fix

### PR DESCRIPTION
**Pull request by rasolca**
- Removed Jenkins unused files from `ci` directory.
- Fixed the calculation of the value for the SLURM `-c` flag.

### CODE REVIEW

**Comment by rasolca** [comment]
Notes:
- HPX default behaviour with `--hpx:use_process_mask` creates an HPX thread for each physical core.
- SLURM default binding method binds fills threads of the same physical core first.

**Comment by rasolca** [comment]
bors try

**Review by albestro — APPROVED** [review]
LGTM

**Comment by rasolca** [comment]
bors try
(Using this PR to debug a strange "Memory required by task is not available" slurm error that pops up randomly (not specific to this PR)).

**Comment by rasolca** [comment]
@haampie Is any other project having problems with the CI after the maintenance?
I'm randomly seeing `srun: error: Unable to create step for job 29975643: Memory required by task is not available` on mc partition and `srun: error: Unable to create step for job 29975549: Invalid generic resource (gres) specification` on gpu.
All these errors disappear when retrying the failed tests.
(see https://gitlab.com/cscs-ci/eth-cscs/DLA-Future/-/pipelines/272133930 for more detail.)

**Comment by albestro** [comment]
> @haampie Is any other project having problems with the CI after the maintenance?
> I'm randomly seeing `srun: error: Unable to create step for job 29975643: Memory required by task is not available` on mc partition and `srun: error: Unable to create step for job 29975549: Invalid generic resource (gres) specification` on gpu.
> All these errors disappear when retrying the failed tests.
> (see https://gitlab.com/cscs-ci/eth-cscs/DLA-Future/-/pipelines/272133930 for more detail.)

I had the same problem, I was not able to re-run it from the gitlab UI, so I did `bors try` a second-time. It failed the same way. I'm going to open an issue to keep track of this.

**Comment by rasolca** [comment]
bors try
(run pipeline on dom for debugging purpose)

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by haampie** [comment]
bors try-

**Comment by haampie** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by haampie** [comment]
at this point does it make sense to dynamically generate labels and everything? might as just hard-code them?

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try
(going back to workaround as Victor solution failed)

**Comment by rasolca** [comment]
bors try

**Comment by rasolca** [comment]
bors try
(going back to workaround as Victor solution failed)

**Comment by rasolca** [comment]
bors try-

**Comment by rasolca** [comment]
bors try

**Comment by haampie** [comment]
reliable it is not :(

bors try

**Comment by rasolca** [comment]
bors try
(I hope the system got stable now...)

**Pull request merged**
