### PR TITLE
CI: revert CI workaround

### PR DESCRIPTION
**Pull request by rasolca**
This PR is needed to debug the correct CI setup.

### CODE REVIEW

**Comment by rasolca** [comment]
bors try

**Comment by haampie** [comment]
when pulling without srun:

bors try

**Comment by haampie** [comment]
well... i'm calling it a slurm bug

**Comment by rasolca** [comment]
bors try
Remove 5 rank tests, maybe it's causing problems as not all the cores are used.

**Comment by rasolca** [comment]
bors try
This time really without 5 ranks...

**Comment by rasolca** [comment]
bors try
Let's ensure that the previous success was not a lucky alignment of all the stars, planets and asteroids....

**Comment by haampie** [comment]
So the idea right now is that there's a bug in slurm where it realizes not all CPUs are used, then it tried to schedule a job, but it's marked exclusive, there are not enough CPUs for it, and it fails?

**Comment by rasolca** [comment]
I think that now we can keep the broadcast test with 4 ranks and go back to the original CI pipeline.

**Review by albestro — APPROVED** [review]
It embeds also #346, which can be closed.

Compared differences with #336, it seems all back to normal. So, LGTM.

**Pull request merged**
