### PR TITLE
Fix Compiler ID in CMake (relevant for warnings)

### PR DESCRIPTION
**Pull request by albestro**
I just realized that I used the wrong compiler ID as a trigger for a couple of warnings...

### CODE REVIEW

**Comment by albestro** [comment]
bors try

**Comment by albestro** [comment]
Affected flags are

```
-Wsign-conversion
-Wfloat-conversion
```

**Comment by albestro** [comment]
bors try

**Review by rasolca — APPROVED** [review]

**Comment by rasolca** [comment]
bors try

**Pull request merged**
