### PR TITLE
Port to pika 0.10.0

### PR DESCRIPTION
**Pull request by msimberg**
Still needs:

- [x] spack commit update
- [x] `find_package(pika)` update (no change)
- [x] `package.py` update (no change)
- [x] wait for #642 to be merged

~Not ready, but I'd like to have at least one CI run with pika@main before I make the final pika 0.10.0 release.~

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
All seems ok here. This is on hold at least until #642 is merged.

**Comment by msimberg** [comment]
This is only a spack commit hash bump in the end since 0.10.0 contains no breaking changes.

**Comment by msimberg** [comment]
bors try

**Review by rasolca — APPROVED** [review]

**Pull request merged**
