### PR TITLE
Eigensolver distributed pipeline

### LINKED ISSUE #662: Distributed MC eigensolver pipeline
- [ ] standard
- [ ] generalized

### LINKED ISSUE #663: Distributed MC eigensolver miniapp
- [ ] standard
- [ ] generalized

### PR DESCRIPTION
**Pull request by albestro**
Close #662
Close #663 

This PR targets both backends but, since not all algorithms are ready for both of them, the GPU version will be constrained to work just on a single node (with the available local implementation).

note: Eigensolver does not still support band size (see #701 and #702)

- Add Eigensolver Distributed MC (SEP/GEP)
- Add Eigensolver Distributed GPU (SEP/GEP)
- Add test for Eigensolver Distributed
- Enable Distributed miniapp for Eigensolver (SEP/GEP)

Waiting for algorithms support for distributed version (required):
- [x] #698
- [x] #601

Other relevant things are:
- [x] #683 

TODO:
- [x] Investigate GEP deadlock (see #729 and https://github.com/eth-cscs/DLA-Future/pull/704/commits/f80c2fe31a277849117d3749245e579940196407)
- [ ] Add documentation
- [x] Add test Distributed SEP GPU
- [x] Add Distributed GEP implementation
- [x] Add tests Distributed GEP MC/GPU
- [ ] Add constraints according to limitations at the date of merge
- [x] Cleanup test to be more DRY (e.g. variadic template parameter for optional grid)

### CODE REVIEW

**Comment by albestro** [comment]
bors try

**Review by teonnik — APPROVED** [review]
LGTM!

**Review by rasolca — APPROVED** [review]

**Review by msimberg — APPROVED** [review]
:tada:

**Comment by rasolca** [comment]
@albestro
I merge it and let the last changes for GPU (#728 has been merged) for another PR.

**Pull request merged**
