### PR TITLE
Use std::atomic in place of volatile in test

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Comment by msimberg** [comment]
bors try

**Comment by msimberg** [comment]
bors try

**Comment by albestro** [comment]
I was wondering why I didn't used `bool` in the first place...what about changing them now?

**Comment by rasolca** [comment]
bors try

**Review by teonnik — APPROVED** [review]

**Comment by msimberg** [comment]
> I was wondering why I didn't used `bool` in the first place...what about changing them now?

Good idea! Didn't think about that at all. I've changed them to `bool`s now.

Not sure what bors is trying to tell us...

**Comment by msimberg** [comment]
bors try

**Comment by rasolca** [comment]
The reason bors is failing is that some files of a git clone has been wiped-out by the scratch monthly cleanup.
Asked @haampie to fix it.

**Comment by rasolca** [comment]
bors try

**Review by rasolca — APPROVED** [review]

**Review by albestro — APPROVED** [review]

**Pull request merged**
