### PR TITLE
Add documentation link for 0.4.1 release

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Review by rasolca — COMMENTED** [review]
Wouldn't be better to merge to master and then cherry-pick? Otherwise we lose the link in v0.5.0.

**Comment by msimberg** [comment]
> Wouldn't be better to merge to master and then cherry-pick? Otherwise we lose the link in v0.5.0.

Either way. In the release procedure there is a merge-to-master step right now which would bring the link to master anyway, but I see you've commented about that. If you prefer I can:
- change the base of this PR to `master`
- change the instructions in the release procedure to add the link to `master`, then cherry-pick
?

**Comment by msimberg** [comment]
Updated base branch to `master`.

**Comment by rasolca** [comment]
Mhm... Why are github actions not starting?

**Pull request merged**
