### PR TITLE
Add support to all miniapps in plotting scripts 

### PR DESCRIPTION
**Pull request by rasolca**
Solves #664.

### CODE REVIEW

**Review by msimberg — APPROVED** [review]

**Comment by rasolca** [comment]
Note: I didn't touch "miniapp_reduction_to_band" as @albestro is already working on it in #726

**Comment by rasolca** [comment]
I'm not happy with all the code duplication. I'll try to refactor the code a little bit.

**Review by msimberg — APPROVED** [review]

**Review by albestro — APPROVED** [review]
LGTM

**Comment by rasolca** [comment]
cscs-ci run

**Pull request merged**
