### PR TITLE
Remove unused tile sender from `bt_band_to_tridiag/impl.h`

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Comment by msimberg** [comment]
cscs-ci run

**Review by albestro — APPROVED** [review]
Good catch! Thanks

**Comment by msimberg** [comment]
Marking temporarily as a draft, there might be more of these...

**Comment by msimberg** [comment]
> Marking temporarily as a draft, there might be more of these...

False alarm.

**Review by rasolca — APPROVED** [review]

**Pull request merged**
