### PR TITLE
Enable warnings as error for all languages

### LINKED ISSUE #740: AMD CI does not report warnings as errors
> I've seen them while building in my VM, but actually if you access the complete raw log of the CI, you can find them 😉
> 
> It seems that warning are enabled but they are not considered errors as for other builds.

When we call cublas/solver rocblas/solver we should make sure that the integer type is correct (as e.g https://github.com/eth-cscs/DLA-Future/blob/master/include/dlaf/blas/tile.h#L392-L404) such that warnings should not be generated.

Moreover the variant `+ci-test` should enable `-Werror`. https://github.com/eth-cscs/DLA-Future/blob/master/spack/packages/dla-future/package.py#L128
Can you please check why it is not the case?

Do you want to fix these problems in this PR or in a new one?

_Originally posted by @rasolca in https://github.com/eth-cscs/DLA-Future/issues/739#issuecomment-1339153660_

### PR DESCRIPTION
**Pull request by albestro**
Fix #740

With `+ci-test` variant, we were passing `-Werror` to CMake, but just for the C++ language, and not for GPU specific ones.

### CODE REVIEW

**Comment by albestro** [comment]
cscs-ci run

**Comment by albestro** [comment]
This CI run should result in an error at least for the AMD build (not sure about CUDA).

If it fails, it is a success 😄

After that, I will fork this PR trying to fix existing warnings.

**Comment by albestro** [comment]
CI now reports error also for AMD. No warnings were reported for NVIDIA, so I will just have to target the AMD build.

**Review by msimberg — APPROVED** [review]

**Comment by albestro** [comment]
If no other change is required, this can be merged without being re-tested, since it has been tested the last commit merged from the forked PR (but super-powers are needed in that case).

**Review by teonnik — APPROVED** [review]

**Review by rasolca — APPROVED** [review]

**Comment by rasolca** [comment]
cscs-ci run

**Pull request merged**
