### PR TITLE
[WIP] Use free functions instead of lambdas stored in variables

### PR DESCRIPTION
**Pull request by teonnik**
This fixes : #320 .

Currently there are 3 tests failing:
- test_reduce (Signal 11: Segfault - SIGSEGV)
- test_norm (Signal 9: Killed - SIGKILL)
- test_cholesky (Signal 9: Killed - SIGKILL)

The reasons are being investigated.

Note: `to_SizeType` isn't used anywhere, that is why I removed it.

### CODE REVIEW

**Comment by albestro** [comment]
Reporting here too, just for reference.

```
ialberto@daint101:~/workspace/dla-future_test/build> git rev-parse HEAD
535b53ada5ed68739fb92dc2bbd9cf4ac873044a
ialberto@daint101:~/workspace/dla-future_test/build> gcc --version
gcc (GCC) 8.3.0 20190222 (Cray Inc.)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

...

100% tests passed, 0 tests failed out of 32
Label Time Summary:
RANK_1    =  22.50 sec*proc (16 tests)
RANK_2    =   1.27 sec*proc (1 test)
RANK_4    =   6.39 sec*proc (4 tests)
RANK_5    =   2.56 sec*proc (2 tests)
RANK_6    =  18.77 sec*proc (9 tests)
Total Test time (real) =  51.53 sec
```

**Comment by teonnik** [comment]
All tests pass with `mpich@3.2.1` while 3 of them fail (mentioned above) with `mpich@3.4.1` (the newest MPICH version). The issue is perhaps better investigated elsewhere as it is unlikely to be due to the changes in this PR.

**Comment by teonnik** [comment]
bors try

**Review by albestro — APPROVED** [review]

**Review by rasolca — APPROVED** [review]
LGTM
I see [WIP] in the title, but this PR is not a draft, therefore I'm not sure if I can merge this changes.

**Comment by teonnik** [comment]
Yes, it should be merged. I forgot to update the title when I converted it from draft to open. You shouldn't have written it in the first place as draft is pretty clear. :)

**Pull request merged**
