### PR TITLE
Add CI configuration with ROCm and stdexec

### PR DESCRIPTION
**Pull request by msimberg**
Adds a HIP CI configuration with stdexec enabled.

### CODE REVIEW

**Comment by msimberg** [comment]
cscs-ci run

**Comment by msimberg** [comment]
cscs-ci run

**Comment by msimberg** [comment]
cscs-ci run

**Comment by msimberg** [comment]
cscs-ci run

**Comment by msimberg** [comment]
cscs-ci run

**Comment by msimberg** [comment]
cscs-ci run

**Review by rasolca — APPROVED** [review]

**Pull request merged**
